OverSim: CommonAPIMessage Class Reference
CommonAPIMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>