OverSim: ParetoChurn Class Reference
ParetoChurn Class Reference
Lifetime churn based on shifted pareto distribution.
#include <ParetoChurn.h>