OverSim: PastryStateMessage Class Reference
PastryStateMessage Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>