OverSim: P2pnsRegisterCall Class Reference
P2pnsRegisterCall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>