OverSim: P2pnsResolveCall Class Reference
P2pnsResolveCall Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>