OverSim: P2pnsResolveResponse Class Reference
P2pnsResolveResponse Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>