OverSim: XmlRpc::XmlRpcServer Class Reference
XmlRpc::XmlRpcServer Class Reference
A class to handle XML RPC requests.
#include <XmlRpcServer.h>