OverSim: ChurnMessage Class Reference
ChurnMessage Class Reference
Class generated from common/Churn.msg by opp_msgc.
#include <Churn_m.h>