OverSim: ZeroconfConnector Class Reference
ZeroconfConnector Class Reference
Zeroconf module.
#include <ZeroconfConnector.h>
Public Member Functions
ZeroconfConnector ()
~ZeroconfConnector ()
void announceService (const NodeHandle &node)
Announce bootstrap service in the local domain.
void revokeService ()
Withdraw bootstrap service in the local domain.
bool isEnabled ()
Detailed Description
Zeroconf module.
Module for retrieving bootstrap nodes via Zeroconf (AVAHI connector)
Author:
Bin Zheng
See also:
BootstrapList
Definition at line 188 of file ZeroconfConnector.h.
Constructor & Destructor Documentation
ZeroconfConnector::ZeroconfConnector () [inline]
Definition at line 191 of file ZeroconfConnector.h.
{};
ZeroconfConnector::~ZeroconfConnector () [inline]
Definition at line 192 of file ZeroconfConnector.h.
{};
Member Function Documentation
void ZeroconfConnector::announceService (const NodeHandle & node) [inline]
Announce bootstrap service in the local domain.
Parameters:
node pointer of the local overlay node
Definition at line 199 of file ZeroconfConnector.h.
Referenced by BootstrapList::registerBootstrapNode().
{};
bool ZeroconfConnector::isEnabled () [inline]
Definition at line 211 of file ZeroconfConnector.h.
Referenced by BootstrapList::initializeApp().
{ return false; };
void ZeroconfConnector::revokeService () [inline]
Withdraw bootstrap service in the local domain.
Definition at line 204 of file ZeroconfConnector.h.
Referenced by BootstrapList::removeBootstrapNode().
{};
The documentation for this class was generated from the following file:
ZeroconfConnector.h