OverSim: GameAPIListMessage Class Reference
GameAPIListMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>