OverSim: PastryRoutingRowRequestMessage Class Reference
PastryRoutingRowRequestMessage Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>