OverSim: XmlRpc::XmlRpcErrorHandler Class Reference
XmlRpc::XmlRpcErrorHandler Class Reference
An interface allowing custom handling of error message reporting.
#include <XmlRpc.h>