OverSim: NiceMulticastMessage Class Reference
NiceMulticastMessage Class Reference
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
#include <NiceMessage_m.h>