OverSim: NiceMessage Class Reference
NiceMessage Class Reference
Class generated from overlay/nice/NiceMessage.msg by opp_msgc.
#include <NiceMessage_m.h>