OverSim: GIASearchAppMessage Class Reference
GIASearchAppMessage Class Reference
Class generated from common/ExtAPIMessages.msg by opp_msgc.
#include <ExtAPIMessages_m.h>