OverSim: PubSubTimer Class Reference
PubSubTimer Class Reference
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
#include <PubSubMessage_m.h>
Public Member Functions
PubSubTimer (const char *name=NULL, int kind=0)
PubSubTimer (const PubSubTimer &other)
virtual ~PubSubTimer ()
PubSubTimer & operator= (const PubSubTimer &other)
virtual PubSubTimer * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getType () const
virtual void setType (int type_var)
virtual int getSubspaceId () const
virtual void setSubspaceId (int subspaceId_var)
Protected Member Functions
bool operator== (const PubSubTimer &)
Protected Attributes
int type_var
int subspaceId_var
Detailed Description
Class generated from overlay/pubsubmmog/PubSubMessage.msg by opp_msgc.
 message PubSubTimer
 {
         int type enum(PubSubTimerType);
         int subspaceId;
 }
Definition at line 126 of file PubSubMessage_m.h.
Constructor & Destructor Documentation
PubSubTimer::PubSubTimer (const char * name = NULL, int kind = 0)
Referenced by dup().
PubSubTimer::PubSubTimer (const PubSubTimer & other)
virtual PubSubTimer::~PubSubTimer () [virtual]
Member Function Documentation
virtual PubSubTimer* PubSubTimer::dup () const [inline, virtual]
Definition at line 140 of file PubSubMessage_m.h.
{return new PubSubTimer(*this);}
virtual int PubSubTimer::getSubspaceId () const [virtual]
Referenced by PubSubMMOG::handleParentTimeout().
virtual int PubSubTimer::getType () const [virtual]
Referenced by PubSubMMOG::startTimer().
PubSubTimer& PubSubTimer::operator= (const PubSubTimer & other)
bool PubSubTimer::operator== (const PubSubTimer &) [protected]
virtual void PubSubTimer::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void PubSubTimer::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void PubSubTimer::setSubspaceId (int subspaceId_var) [virtual]
Referenced by PubSubLobby::failedNode(), and PubSubMMOG::handleBackupCall().
virtual void PubSubTimer::setType (int type_var) [virtual]
Referenced by PubSubLobby::failedNode(), PubSubMMOG::handleBackupCall(), and PubSubMMOG::initializeOverlay().
Member Data Documentation
int PubSubTimer::subspaceId_var [protected]
Definition at line 130 of file PubSubMessage_m.h.
int PubSubTimer::type_var [protected]
Definition at line 129 of file PubSubMessage_m.h.
The documentation for this class was generated from the following file:
PubSubMessage_m.h