OverSim: I3QueryReplyMessage_Base Class Reference
I3QueryReplyMessage_Base Class Reference
Class generated from applications/i3/I3Message.msg by opp_msgc.
#include <I3Message_m.h>