OverSim: GIAsearch Class Reference
GIAsearch Class Reference
Class generated from common/ExtAPIMessages.msg by opp_msgc.
#include <ExtAPIMessages_m.h>