OverSim: GlobalTraceManagerMessage Class Reference
GlobalTraceManagerMessage Class Reference
Class generated from common/GlobalTraceManager.msg by opp_msgc.
#include <GlobalTraceManager_m.h>
Public Member Functions
GlobalTraceManagerMessage (const char *name=NULL, int kind=0)
GlobalTraceManagerMessage (const GlobalTraceManagerMessage &other)
virtual ~GlobalTraceManagerMessage ()
GlobalTraceManagerMessage & operator= (const GlobalTraceManagerMessage &other)
virtual GlobalTraceManagerMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual int getInternalNodeId () const
virtual void setInternalNodeId (int internalNodeId_var)
virtual int getLineNumber () const
virtual void setLineNumber (int lineNumber_var)
Protected Member Functions
bool operator== (const GlobalTraceManagerMessage &)
Protected Attributes
int internalNodeId_var
int lineNumber_var
Detailed Description
Class generated from common/GlobalTraceManager.msg by opp_msgc.
 packet GlobalTraceManagerMessage
 {
         int internalNodeId;
         int lineNumber;
 }
Definition at line 28 of file GlobalTraceManager_m.h.
Constructor & Destructor Documentation
GlobalTraceManagerMessage::GlobalTraceManagerMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
GlobalTraceManagerMessage::GlobalTraceManagerMessage (const GlobalTraceManagerMessage & other)
virtual GlobalTraceManagerMessage::~GlobalTraceManagerMessage () [virtual]
Member Function Documentation
virtual GlobalTraceManagerMessage* GlobalTraceManagerMessage::dup () const [inline, virtual]
Definition at line 42 of file GlobalTraceManager_m.h.
{return new GlobalTraceManagerMessage(*this);}
virtual int GlobalTraceManagerMessage::getInternalNodeId () const [virtual]
Referenced by GlobalTraceManager::handleMessage().
virtual int GlobalTraceManagerMessage::getLineNumber () const [virtual]
GlobalTraceManagerMessage& GlobalTraceManagerMessage::operator= (const GlobalTraceManagerMessage & other)
bool GlobalTraceManagerMessage::operator== (const GlobalTraceManagerMessage &) [protected]
virtual void GlobalTraceManagerMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void GlobalTraceManagerMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void GlobalTraceManagerMessage::setInternalNodeId (int internalNodeId_var) [virtual]
Referenced by GlobalTraceManager::scheduleNextEvent().
virtual void GlobalTraceManagerMessage::setLineNumber (int lineNumber_var) [virtual]
Referenced by GlobalTraceManager::scheduleNextEvent().
Member Data Documentation
int GlobalTraceManagerMessage::internalNodeId_var [protected]
Definition at line 31 of file GlobalTraceManager_m.h.
int GlobalTraceManagerMessage::lineNumber_var [protected]
Definition at line 32 of file GlobalTraceManager_m.h.
The documentation for this class was generated from the following file:
GlobalTraceManager_m.h