OverSim: GiaIDMessage Class Reference
GiaIDMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>