OverSim: CompReadyMessage Class Reference
CompReadyMessage Class Reference
Class generated from common/CommonMessages.msg by opp_msgc.
#include <CommonMessages_m.h>
Public Member Functions
CompReadyMessage (const char *name=NULL, int kind=0)
CompReadyMessage (const CompReadyMessage &other)
virtual ~CompReadyMessage ()
CompReadyMessage & operator= (const CompReadyMessage &other)
virtual CompReadyMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual bool getReady () const
virtual void setReady (bool ready_var)
virtual int getComp () const
virtual void setComp (int comp_var)
Protected Member Functions
bool operator== (const CompReadyMessage &)
Protected Attributes
bool ready_var
int comp_var
Detailed Description
Class generated from common/CommonMessages.msg by opp_msgc.
 packet CompReadyMessage
 {
     bool ready;
     int comp enum(CompType);
 }
Definition at line 833 of file CommonMessages_m.h.
Constructor & Destructor Documentation
CompReadyMessage::CompReadyMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
CompReadyMessage::CompReadyMessage (const CompReadyMessage & other)
virtual CompReadyMessage::~CompReadyMessage () [virtual]
Member Function Documentation
virtual CompReadyMessage* CompReadyMessage::dup () const [inline, virtual]
Definition at line 847 of file CommonMessages_m.h.
{return new CompReadyMessage(*this);}
virtual int CompReadyMessage::getComp () const [virtual]
Referenced by BaseOverlay::handleMessage(), XmlRpcInterface::handleReadyMessage(), SimpleGameClient::handleReadyMessage(), SimMud::handleReadyMessage(), Scribe::handleReadyMessage(), P2pns::handleReadyMessage(), NeighborCache::handleReadyMessage(), and ALMTest::handleReadyMessage().
virtual bool CompReadyMessage::getReady () const [virtual]
Referenced by BaseOverlay::handleMessage(), XmlRpcInterface::handleReadyMessage(), SimpleGameClient::handleReadyMessage(), SimMud::handleReadyMessage(), Scribe::handleReadyMessage(), P2pns::handleReadyMessage(), NeighborCache::handleReadyMessage(), and ALMTest::handleReadyMessage().
CompReadyMessage& CompReadyMessage::operator= (const CompReadyMessage & other)
bool CompReadyMessage::operator== (const CompReadyMessage &) [protected]
virtual void CompReadyMessage::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void CompReadyMessage::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void CompReadyMessage::setComp (int comp_var) [virtual]
Referenced by Vast::changeState(), Quon::changeState(), PubSubMMOG::handleAppMessage(), NTree::handleAppMessage(), Quon::handleNodeGracefulLeaveNotification(), Vast::handleNodeLeaveNotification(), SimMud::handleReadyMessage(), Scribe::handleReadyMessage(), PubSubMMOG::handleSubscriptionResponse(), PubSubMMOG::handleTimerEvent(), NTree::handleTimerEvent(), BaseApp::sendReadyMessage(), and BaseOverlay::setOverlayReady().
virtual void CompReadyMessage::setReady (bool ready_var) [virtual]
Referenced by Vast::changeState(), Quon::changeState(), PubSubMMOG::handleAppMessage(), NTree::handleAppMessage(), Quon::handleNodeGracefulLeaveNotification(), Vast::handleNodeLeaveNotification(), Scribe::handleReadyMessage(), PubSubMMOG::handleSubscriptionResponse(), PubSubMMOG::handleTimerEvent(), NTree::handleTimerEvent(), BaseApp::sendReadyMessage(), and BaseOverlay::setOverlayReady().
Member Data Documentation
int CompReadyMessage::comp_var [protected]
Definition at line 837 of file CommonMessages_m.h.
bool CompReadyMessage::ready_var [protected]
Definition at line 836 of file CommonMessages_m.h.
The documentation for this class was generated from the following file:
CommonMessages_m.h