OverSim: NTree Class Reference
NTree Class Reference
A p2p protocol for MMOGs and virtual worlds.
#include <NTree.h>