OverSim: BaseOverlay Class Reference
BaseOverlay Class Reference
Base class for overlays.
#include <BaseOverlay.h>