OverSim: SearchResponseMessage Class Reference
SearchResponseMessage Class Reference
Class generated from overlay/gia/GiaMessage.msg by opp_msgc.
#include <GiaMessage_m.h>