OverSim: TransportAddress Class Reference
TransportAddress Class Reference
This class implements a common transport address.
#include <TransportAddress.h>