OverSim: NTreeGroupDeleteMessage Class Reference
NTreeGroupDeleteMessage Class Reference
Class generated from overlay/ntree/NTree.msg by opp_msgc.
#include <NTree_m.h>