OverSim: XmlRpc::XmlRpcServerMethod Class Reference
XmlRpc::XmlRpcServerMethod Class Reference
Abstract class representing a single RPC method.
#include <XmlRpcServerMethod.h>