OverSim: XmlRpc::XmlRpcException Class Reference
XmlRpc::XmlRpcException Class Reference
A class representing an error.
#include <XmlRpcException.h>
Public Member Functions
XmlRpcException (const std::string &message, int code=-1)
Constructor.
const std::string & getMessage () const
Return the error message.
int getCode () const
Return the error code.
Private Attributes
std::string _message
int _code
Detailed Description
A class representing an error.
If server methods throw this exception, a fault response is returned to the client.
Definition at line 29 of file XmlRpcException.h.
Constructor & Destructor Documentation
XmlRpc::XmlRpcException::XmlRpcException (const std::string & message, int code = -1) [inline]
Constructor.
Parameters:
message A descriptive error message
code An integer error code
Definition at line 34 of file XmlRpcException.h.
                                                           :
        _message(message), _code(code) {}
Member Function Documentation
int XmlRpc::XmlRpcException::getCode () const [inline]
Return the error code.
Definition at line 41 of file XmlRpcException.h.
Referenced by XmlRpc::XmlRpcServer::executeMulticall(), and XmlRpc::XmlRpcServer::executeRequest().
{ return _code; }
const std::string& XmlRpc::XmlRpcException::getMessage () const [inline]
Return the error message.
Definition at line 38 of file XmlRpcException.h.
Referenced by XmlRpc::XmlRpcServer::executeMulticall(), and XmlRpc::XmlRpcServer::executeRequest().
{ return _message; }
Member Data Documentation
int XmlRpc::XmlRpcException::_code [private]
Definition at line 45 of file XmlRpcException.h.
Referenced by getCode().
std::string XmlRpc::XmlRpcException::_message [private]
Definition at line 44 of file XmlRpcException.h.
Referenced by getMessage().
The documentation for this class was generated from the following file:
XmlRpcException.h