OverSim: BaseApp Class Reference
BaseApp Class Reference
Base class for applications.
#include <BaseApp.h>