OverSim: VastDiscardMessage Class Reference
VastDiscardMessage Class Reference
Class generated from overlay/vast/Vast.msg by opp_msgc.
#include <Vast_m.h>