OverSim: PastryLeafsetMessage Class Reference
PastryLeafsetMessage Class Reference
Class generated from overlay/pastry/PastryMessage.msg by opp_msgc.
#include <PastryMessage_m.h>