OverSim: ScribePublishResponse Class Reference
ScribePublishResponse Class Reference
Class generated from applications/scribe/ScribeMessage.msg by opp_msgc.
#include <ScribeMessage_m.h>