OverSim: ParetoChurnMessage Class Reference
ParetoChurnMessage Class Reference
Class generated from common/Churn.msg by opp_msgc.
#include <Churn_m.h>