OverSim: base64< _E, _Tr >::three2four Struct Reference
base64< _E, _Tr >::three2four Struct Reference
#include <base64.h>
Public Member Functions
void zero ()
byte_t get_0 () const
byte_t get_1 () const
byte_t get_2 () const
void set_0 (byte_t _ch)
void set_1 (byte_t _ch)
void set_2 (byte_t _ch)
int b64_0 () const
int b64_1 () const
int b64_2 () const
int b64_3 () const
void b64_0 (int _ch)
void b64_1 (int _ch)
void b64_2 (int _ch)
void b64_3 (int _ch)
Private Attributes
byte_t _data [3]
Detailed Description
template<class _E = char, class _Tr = std::char_traits<_E>>
struct base64< _E, _Tr >::three2four
Definition at line 87 of file base64.h.
Member Function Documentation
template<class _E = char, class _Tr = std::char_traits<_E>> int base64< _E, _Tr >::three2four::b64_0 () const [inline]
Definition at line 128 of file base64.h.
Referenced by base64< _E, _Tr >::get(), and base64< _E, _Tr >::put().
{return (_data[0] & _1111_1100) >> 2;}
template<class _E = char, class _Tr = std::char_traits<_E>> void base64< _E, _Tr >::three2four::b64_0 (int _ch) [inline]
Definition at line 133 of file base64.h.
{_data[0] = ((_ch & _0011_1111) << 2) | (_0000_0011 & _data[0]);}
template<class _E = char, class _Tr = std::char_traits<_E>> int base64< _E, _Tr >::three2four::b64_1 () const [inline]
Definition at line 129 of file base64.h.
Referenced by base64< _E, _Tr >::get(), and base64< _E, _Tr >::put().
{return ((_data[0] & _0000_0011) << 4) + ((_data[1] & _1111_0000)>>4);}
template<class _E = char, class _Tr = std::char_traits<_E>> void base64< _E, _Tr >::three2four::b64_1 (int _ch) [inline]
Definition at line 135 of file base64.h.
{
                        _data[0] = ((_ch & _0011_0000) >> 4) | (_1111_1100 & _data[0]);
                        _data[1] = ((_ch & _0000_1111) << 4) | (_0000_1111 & _data[1]); }
template<class _E = char, class _Tr = std::char_traits<_E>> int base64< _E, _Tr >::three2four::b64_2 () const [inline]
Definition at line 130 of file base64.h.
Referenced by base64< _E, _Tr >::get(), and base64< _E, _Tr >::put().
{return ((_data[1] & _0000_1111) << 2) + ((_data[2] & _1100_0000)>>6);}
template<class _E = char, class _Tr = std::char_traits<_E>> void base64< _E, _Tr >::three2four::b64_2 (int _ch) [inline]
Definition at line 139 of file base64.h.
{
                        _data[1] = ((_ch & _0011_1100) >> 2) | (_1111_0000 & _data[1]);
                        _data[2] = ((_ch & _0000_0011) << 6) | (_0011_1111 & _data[2]); }
template<class _E = char, class _Tr = std::char_traits<_E>> int base64< _E, _Tr >::three2four::b64_3 () const [inline]
Definition at line 131 of file base64.h.
Referenced by base64< _E, _Tr >::get(), and base64< _E, _Tr >::put().
{return (_data[2] & _0011_1111);}
template<class _E = char, class _Tr = std::char_traits<_E>> void base64< _E, _Tr >::three2four::b64_3 (int _ch) [inline]
Definition at line 143 of file base64.h.
{
                        _data[2] = (_ch & _0011_1111) | (_1100_0000 & _data[2]);}
template<class _E = char, class _Tr = std::char_traits<_E>> byte_t base64< _E, _Tr >::three2four::get_0 () const [inline]
Definition at line 96 of file base64.h.
Referenced by base64< _E, _Tr >::get().
                {
                        return _data[0];
                }
template<class _E = char, class _Tr = std::char_traits<_E>> byte_t base64< _E, _Tr >::three2four::get_1 () const [inline]
Definition at line 100 of file base64.h.
Referenced by base64< _E, _Tr >::get().
                {
                        return _data[1];
                }
template<class _E = char, class _Tr = std::char_traits<_E>> byte_t base64< _E, _Tr >::three2four::get_2 () const [inline]
Definition at line 104 of file base64.h.
Referenced by base64< _E, _Tr >::get().
                {
                        return _data[2];
                }
template<class _E = char, class _Tr = std::char_traits<_E>> void base64< _E, _Tr >::three2four::set_0 (byte_t _ch) [inline]
Definition at line 109 of file base64.h.
Referenced by base64< _E, _Tr >::put().
                {
                        _data[0] = _ch;
                }
template<class _E = char, class _Tr = std::char_traits<_E>> void base64< _E, _Tr >::three2four::set_1 (byte_t _ch) [inline]
Definition at line 114 of file base64.h.
Referenced by base64< _E, _Tr >::put().
                {
                        _data[1] = _ch;
                }
template<class _E = char, class _Tr = std::char_traits<_E>> void base64< _E, _Tr >::three2four::set_2 (byte_t _ch) [inline]
Definition at line 119 of file base64.h.
Referenced by base64< _E, _Tr >::put().
                {
                        _data[2] = _ch;
                }
template<class _E = char, class _Tr = std::char_traits<_E>> void base64< _E, _Tr >::three2four::zero () [inline]
Definition at line 89 of file base64.h.
Referenced by base64< _E, _Tr >::get(), and base64< _E, _Tr >::put().
                {
                        _data[0] = 0;
                        _data[1] = 0;
                        _data[2] = 0;
                }
Member Data Documentation
template<class _E = char, class _Tr = std::char_traits<_E>> byte_t base64< _E, _Tr >::three2four::_data[3] [private]
Definition at line 147 of file base64.h.
Referenced by base64< _E, _Tr >::three2four::b64_0(), base64< _E, _Tr >::three2four::b64_1(), base64< _E, _Tr >::three2four::b64_2(), base64< _E, _Tr >::three2four::b64_3(), base64< _E, _Tr >::three2four::get_0(), base64< _E, _Tr >::three2four::get_1(), base64< _E, _Tr >::three2four::get_2(), base64< _E, _Tr >::three2four::set_0(), base64< _E, _Tr >::three2four::set_1(), base64< _E, _Tr >::three2four::set_2(), and base64< _E, _Tr >::three2four::zero().
The documentation for this struct was generated from the following file:
base64.h