OverSim: XmlRpcServer.cc File Reference
XmlRpcServer.cc File Reference
#include "XmlRpcServer.h"
#include "XmlRpcServerConnection.h"
#include "XmlRpcServerMethod.h"
#include "XmlRpcSocket.h"
#include "XmlRpcUtil.h"
#include "XmlRpcException.h"
#include "XmlRpc.h"
Classes
class ListMethods
class MethodHelp
Functions
static const std::string LIST_METHODS ("system.listMethods")
static const std::string METHOD_HELP ("system.methodHelp")
static const std::string MULTICALL ("system.multicall")
Detailed Description
Author:
Chris Morley
Definition in file XmlRpcServer.cc.
Function Documentation
static const std::string LIST_METHODS ("system.listMethods") [static]
Referenced by XmlRpc::XmlRpcServer::enableIntrospection().
static const std::string METHOD_HELP ("system.methodHelp") [static]
Referenced by XmlRpc::XmlRpcServer::enableIntrospection(), and MethodHelp::execute().
static const std::string MULTICALL ("system.multicall") [static]
Referenced by XmlRpc::XmlRpcServer::executeMulticall(), and XmlRpc::XmlRpcServer::listMethods().